site_name: prefect-fivetran
site_url: https://pubchimps.github.io/prefect-fivetran
repo_url: https://github.com/pubchimps/prefect-fivetran
edit_uri: /edit/main/docs/
theme:
  name: material
  favicon: img/favicon.ico
  palette:
    primary: blue
    accent: blue
  icon:
    repo: fontawesome/brands/github
  logo:
    img/prefect-logo-mark.png
  font:
    text: Inter
    code: Source Code Pro
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
    - pymdownx.tabbed
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: False
            show_bases: False
            show_signature: False
            heading_level: 1
      watch:
        - prefect_fivetran/
        - README.md

nav:
    - Home: index.md
    - Connectors: connectors.md
    - Clients: clients.md
    - Credentials: credentials.md

